<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-07T17:34:55 IST" name="Suite" finished-at="2025-03-07T17:35:32 IST" duration-ms="36944">
    <groups>
      <group name="purchase">
        <method signature="StandAlone.sumitOrder(java.util.HashMap)[pri:0, instance:frameWork.StandAlone@35dab4eb]" name="sumitOrder" class="frameWork.StandAlone"/>
      </group> <!-- purchase -->
    </groups>
    <test started-at="2025-03-07T17:34:55 IST" name="Test" finished-at="2025-03-07T17:35:32 IST" duration-ms="36944">
      <class name="frameWork.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:frameWork.ErrorValidation@2eae8e6e]" started-at="2025-03-07T17:34:55 IST" name="launchApplication" finished-at="2025-03-07T17:35:09 IST" duration-ms="13548" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="sumitOrder()[pri:0, instance:frameWork.ErrorValidation@2eae8e6e]" started-at="2025-03-07T17:35:09 IST" name="sumitOrder" finished-at="2025-03-07T17:35:10 IST" duration-ms="799" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Incorrect email or password.> but was:<unknown error occured>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Incorrect email or password.> but was:<unknown error occured>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at frameWork.ErrorValidation.sumitOrder(ErrorValidation.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumitOrder -->
      </class> <!-- frameWork.ErrorValidation -->
      <class name="frameWork.StandAlone">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:frameWork.StandAlone@35dab4eb]" started-at="2025-03-07T17:35:10 IST" name="launchApplication" finished-at="2025-03-07T17:35:16 IST" duration-ms="5333" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="sumitOrder(java.util.HashMap)[pri:0, instance:frameWork.StandAlone@35dab4eb]" started-at="2025-03-07T17:35:16 IST" name="sumitOrder" data-provider="getData" finished-at="2025-03-07T17:35:18 IST" duration-ms="1859" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Jeet!1234, product=BANARSI SAREE, email=jeet@1212gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because the return value of "jitendraSahuCompany.pageObjects.ProductsCataLog.getProductByName(String)" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because the return value of "jitendraSahuCompany.pageObjects.ProductsCataLog.getProductByName(String)" is null
at jitendraSahuCompany.pageObjects.ProductsCataLog.addTocart(ProductsCataLog.java:65)
at frameWork.StandAlone.sumitOrder(StandAlone.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumitOrder -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:frameWork.StandAlone@35dab4eb]" started-at="2025-03-07T17:35:18 IST" name="launchApplication" finished-at="2025-03-07T17:35:24 IST" duration-ms="6754" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="sumitOrder(java.util.HashMap)[pri:0, instance:frameWork.StandAlone@35dab4eb]" started-at="2025-03-07T17:35:24 IST" name="sumitOrder" data-provider="getData" finished-at="2025-03-07T17:35:32 IST" duration-ms="7859" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Jeet!1234, product=ADIDAS ORIGINAL, email=jeet@1212gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumitOrder -->
        <test-method signature="myOrdersTest()[pri:0, instance:frameWork.StandAlone@35dab4eb]" started-at="2025-03-07T17:35:32 IST" name="myOrdersTest" finished-at="2025-03-07T17:35:32 IST" depends-on-methods="frameWork.StandAlone.sumitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method frameWork.StandAlone.myOrdersTest() on instance frameWork.StandAlone@35dab4eb depends on not successfully finished methods 
[frameWork.StandAlone.sumitOrder() on instance frameWork.StandAlone@35dab4eb]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method frameWork.StandAlone.myOrdersTest() on instance frameWork.StandAlone@35dab4eb depends on not successfully finished methods 
[frameWork.StandAlone.sumitOrder() on instance frameWork.StandAlone@35dab4eb]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myOrdersTest -->
      </class> <!-- frameWork.StandAlone -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
